# Generated by Django 4.2.1 on 2023-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_banners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='alt_text',
            field=models.CharField(max_length=300),
        ),
    ]
