# Generated by Django 4.2.1 on 2023-05-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_inquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inquery',
            new_name='Inquiry',
        ),
    ]
