# Generated by Django 4.2.1 on 2023-05-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_subscriptionplans_subscriptionplansfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplans',
            options={'verbose_name_plural': 'Subscription Plans'},
        ),
    ]
