# Generated by Django 4.2.1 on 2023-05-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_subscriptionplans_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='highlight_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
