# Generated by Django 4.2.1 on 2023-05-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_remove_subscriptionplansfeature_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='max_member',
            field=models.IntegerField(null=True),
        ),
    ]
