# Generated by Django 4.2.1 on 2023-05-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_subscriptionplans_max_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplans',
            name='max_member',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
