# Generated by Django 4.2.1 on 2023-05-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_subscribtion_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('detail', models.TextField()),
                ('trainer_img', models.ImageField(upload_to='trainers/')),
            ],
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user_img',
            field=models.ImageField(null=True, upload_to='user_imgs/'),
        ),
    ]
